server:
  port: ${PORT:8080}

spring:
  application:
    name: smart-hospital-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://HQS:HSQ%40123@hqmsystem.4vhpukm.mongodb.net/smarthospital?retryWrites=true&w=majority&appName=HQMsystem}
      auto-index-creation: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

queue:
  avg-service-minutes: 15

logging:
  level:
    com:
      smarthospital: INFO
