server:
  port: ${PORT:8080}

spring:
  application:
    name: smart-hospital-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/smarthospital}
      auto-index-creation: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

queue:
  avg-service-minutes: 15

logging:
  level:
    com.smarthospital: INFO

jwt:
  secret: ${JWT_SECRET:7a62b1668b209a349c8c935492d52f605a9161a073f1d2449557b6f6f1947b74}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
